name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build using node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run 11 --if-present
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _dist 
          PUBLISH_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}